### ISSUE TITLE
Add new game pls

### ISSUE THREAD

**Issue by MrHadiHeidari** [gkhantyln/hamsterKombatPromoKeyGenerator#1]
I really appreciate you 
Add new game pls

**Comment by gkhantyln** [comment]
I have started working on adding a new game. It will be added as soon as possible.

15.08.2024 : 12:54 New Game Added! - Merge Away
16.08.2024 : 12:09 New Game Added! - Twerk Race 3D

**Comment by dhananjayar99** [comment]
**_

> `there are so many deobfuscators here,`

_**

**Comment by gkhantyln** [comment]
No problem, you can use it as you wish. we will test the success rate of the password when it is solved :)

**Comment by lucky2431** [comment]
> I have started working on adding a new game. It will be added as soon as possible.
> 
> 15.08.2024 : 12:54 New Game Added! - Merge Away 16.08.2024 : 12:09 New Game Added! - Twerk Race 3D

Look like twerk not generate keys

**Comment by gkhantyln** [comment]
> > I have started working on adding a new game. It will be added as soon as possible.
> > 15.08.2024 : 12:54 New Game Added! - Merge Away 16.08.2024 : 12:09 New Game Added! - Twerk Race 3D
> 
> Look like twerk not generate keys

It's been code updated and tested. The key has been created. Wait an average of 3 minutes.
